package com.mahilashakti.unnati.ui.screens

import android.content.Intent
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.mahilashakti.unnati.BuildConfig
import com.mahilashakti.unnati.data.repository.MonthlyReport
import com.mahilashakti.unnati.ui.components.*
import com.mahilashakti.unnati.ui.theme.*
import com.mahilashakti.unnati.viewmodel.MainViewModel
import com.google.ai.client.generativeai.GenerativeModel
import kotlinx.coroutines.launch
import java.util.Calendar

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportsScreen(
    viewModel: MainViewModel,
    onBack: () -> Unit
) {
    val cal = remember { Calendar.getInstance() }
    var selectedMonth by remember { mutableIntStateOf(cal.get(Calendar.MONTH) + 1) }
    var selectedYear by remember { mutableIntStateOf(cal.get(Calendar.YEAR)) }
    var report by remember { mutableStateOf<MonthlyReport?>(null) }
    var isGenerating by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()
    val context = LocalContext.current
    val clipboard = LocalClipboardManager.current
    val snackState = remember { SnackbarHostState() }
    var snackMsg by remember { mutableStateOf("") }

    val monthNames = listOf("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")

    LaunchedEffect(snackMsg) {
        if (snackMsg.isNotEmpty()) { snackState.showSnackbar(snackMsg); snackMsg = "" }
    }

    fun generateReportText(r: MonthlyReport): String {
        val sb = StringBuilder()
        sb.appendLine("═══════════════════════════════")
        sb.appendLine("  ${r.groupName}")
        sb.appendLine("  Monthly Report — ${monthNames[r.month - 1]} ${r.year}")
        sb.appendLine("═══════════════════════════════")
        sb.appendLine("Group Capital Collected: ₹${String.format("%,.2f", r.totalCapital)}")
        sb.appendLine("Members: ${r.membersCount}  |  Active Loans: ${r.activeLoansCount}")
        sb.appendLine("Total Loan Outstanding: ₹${String.format("%,.2f", r.totalOutstanding)}")
        sb.appendLine("───────────────────────────────")
        sb.appendLine("MEMBER SUMMARY:")
        sb.appendLine(String.format("%-16s %10s %12s %6s", "Name", "Savings", "Loan Out.", "Score"))
        sb.appendLine("─".repeat(47))
        r.memberRows.forEach { row ->
            sb.appendLine(String.format("%-16s %10s %12s %6d",
                row.name.take(16),
                "₹${String.format("%,.0f", row.savingsThisMonth)}",
                "₹${String.format("%,.0f", row.loanOutstanding)}",
                row.creditScore
            ))
        }
        sb.appendLine("═══════════════════════════════")
        sb.appendLine("Generated by Mahila Shakti Unnati App")
        return sb.toString()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Reports", fontWeight = FontWeight.Bold) },
                navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.Default.ArrowBack, null) } }
            )
        },
        snackbarHost = { SnackbarHost(snackState) }
    ) { padding ->
        LazyColumn(
            modifier = Modifier.fillMaxSize().padding(padding),
            contentPadding = PaddingValues(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            item {
                Card(shape = RoundedCornerShape(16.dp), elevation = CardDefaults.cardElevation(4.dp)) {
                    Column(modifier = Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Text("Generate Monthly Report", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)

                        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                            // Month picker
                            ExposedDropdownMenuBox(
                                expanded = false,
                                onExpandedChange = {},
                                modifier = Modifier.weight(1f)
                            ) {
                                var expanded by remember { mutableStateOf(false) }
                                ExposedDropdownMenuBox(expanded = expanded, onExpandedChange = { expanded = it }) {
                                    OutlinedTextField(
                                        value = monthNames[selectedMonth - 1],
                                        onValueChange = {},
                                        readOnly = true,
                                        label = { Text("Month") },
                                        trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded) },
                                        modifier = Modifier.menuAnchor()
                                    )
                                    ExposedDropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
                                        monthNames.forEachIndexed { i, m ->
                                            DropdownMenuItem(text = { Text(m) }, onClick = { selectedMonth = i + 1; expanded = false })
                                        }
                                    }
                                }
                            }

                            // Year
                            OutlinedTextField(
                                value = selectedYear.toString(),
                                onValueChange = { selectedYear = it.toIntOrNull() ?: selectedYear },
                                label = { Text("Year") },
                                modifier = Modifier.weight(1f),
                                singleLine = true
                            )
                        }

                        Button(
                            onClick = {
                                isGenerating = true
                                scope.launch {
                                    report = viewModel.getMonthlyReport(selectedYear, selectedMonth)
                                    isGenerating = false
                                }
                            },
                            modifier = Modifier.fillMaxWidth(),
                            enabled = !isGenerating
                        ) {
                            if (isGenerating) CircularProgressIndicator(Modifier.size(18.dp), color = Color.White, strokeWidth = 2.dp)
                            else { Icon(Icons.Default.Assessment, null, Modifier.size(18.dp)); Spacer(Modifier.width(8.dp)); Text("Generate Report") }
                        }
                    }
                }
            }

            report?.let { r ->
                val reportText = generateReportText(r)
                item {
                    Card(shape = RoundedCornerShape(16.dp)) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                                Text("Report Preview", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                    IconButton(onClick = {
                                        clipboard.setText(AnnotatedString(reportText))
                                        snackMsg = "Report copied to clipboard!"
                                    }) { Icon(Icons.Default.ContentCopy, null) }
                                    IconButton(onClick = {
                                        val intent = Intent(Intent.ACTION_SEND).apply {
                                            type = "text/plain"
                                            putExtra(Intent.EXTRA_TEXT, reportText)
                                            setPackage("com.whatsapp")
                                        }
                                        try {
                                            context.startActivity(intent)
                                        } catch (e: Exception) {
                                            val fallback = Intent(Intent.ACTION_SEND).apply { type = "text/plain"; putExtra(Intent.EXTRA_TEXT, reportText) }
                                            context.startActivity(Intent.createChooser(fallback, "Share Report"))
                                        }
                                    }) { Icon(Icons.Default.Share, null, tint = Primary) }
                                }
                            }

                            Surface(
                                shape = RoundedCornerShape(8.dp),
                                color = MaterialTheme.colorScheme.surfaceVariant
                            ) {
                                Text(
                                    text = reportText,
                                    modifier = Modifier.padding(12.dp).horizontalScroll(rememberScrollState()),
                                    style = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace)
                                )
                            }

                            Button(
                                onClick = {
                                    val intent = Intent(Intent.ACTION_SEND).apply {
                                        type = "text/plain"
                                        putExtra(Intent.EXTRA_TEXT, reportText)
                                        setPackage("com.whatsapp")
                                    }
                                    try {
                                        context.startActivity(intent)
                                    } catch (e: Exception) {
                                        val fallback = Intent(Intent.ACTION_SEND).apply { type = "text/plain"; putExtra(Intent.EXTRA_TEXT, reportText) }
                                        context.startActivity(Intent.createChooser(fallback, "Share Report"))
                                    }
                                },
                                modifier = Modifier.fillMaxWidth(),
                                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF25D366))
                            ) {
                                Icon(Icons.Default.Share, null, Modifier.size(18.dp))
                                Spacer(Modifier.width(8.dp))
                                Text("Share via WhatsApp")
                            }
                        }
                    }
                }
            }
        }
    }
}

// ─── AI Coach Screen ───────────────────────────────────────────────────────────

data class ChatMessage(val text: String, val isUser: Boolean)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AiCoachScreen(
    memberId: Long,
    viewModel: MainViewModel,
    onBack: () -> Unit
) {
    val allMembers by viewModel.membersWithSavings.collectAsStateWithLifecycle()
    val mws = allMembers.find { it.member.memberId == memberId }

    var messages by remember { mutableStateOf(listOf(
        ChatMessage("Namaskara! 🙏 I am your Mahila Shakti Financial Coach. Ask me anything about savings, loans, interest, or credit scores in simple language!", false)
    )) }
    var input by remember { mutableStateOf("") }
    var isLoading by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()
    val listState = rememberLazyListState()

    val presetQuestions = listOf(
        "What is simple interest?",
        "How is my credit score calculated?",
        "How much loan can I get?",
        "What happens if I miss a payment?",
        "How do SHG loans help women?"
    )

    val model = remember {
        try {
            GenerativeModel(modelName = "gemini-1.5-flash", apiKey = BuildConfig.GEMINI_API_KEY)
        } catch (e: Exception) { null }
    }

    fun sendMessage(text: String) {
        if (text.isBlank()) return
        messages = messages + ChatMessage(text, true)
        input = ""
        isLoading = true

        scope.launch {
            try {
                val context = if (mws != null) {
                    val savings = mws.savings.filter { it.status == "PAID" }.sumOf { it.amount }
                    "Member context: Name=${mws.member.name}, TotalSavings=₹$savings, CreditScore=${mws.member.creditScore}"
                } else "General SHG context"

                val prompt = """You are a friendly financial coach for a Women's Self-Help Group (SHG) app called Mahila Shakti Unnati.
$context
Question: $text
Answer in simple, friendly language. Keep it under 3 sentences. Use ₹ for rupees. You can respond in English or Kannada based on the question language."""

                val response = model?.generateContent(prompt)
                val reply = response?.text ?: "I'm here to help! Please add your Gemini API key in BuildConfig.GEMINI_API_KEY to enable AI responses."
                messages = messages + ChatMessage(reply, false)
            } catch (e: Exception) {
                messages = messages + ChatMessage("Sorry, I couldn't connect to the AI. Please check your internet and API key. Error: ${e.message?.take(80)}", false)
            }
            isLoading = false
            listState.animateScrollToItem(messages.size - 1)
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Surface(shape = CircleShape, color = Primary.copy(0.15f)) {
                            Text("🤖", modifier = Modifier.padding(8.dp))
                        }
                        Column {
                            Text("AI Financial Coach", fontWeight = FontWeight.Bold)
                            Text("Powered by Gemini AI", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.outline)
                        }
                    }
                },
                navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.Default.ArrowBack, null) } }
            )
        }
    ) { padding ->
        Column(modifier = Modifier.fillMaxSize().padding(padding)) {
            // Messages
            LazyColumn(
                state = listState,
                modifier = Modifier.weight(1f).padding(horizontal = 16.dp),
                contentPadding = PaddingValues(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(messages) { msg ->
                    ChatBubble(msg)
                }
                if (isLoading) {
                    item {
                        Row(modifier = Modifier.fillMaxWidth().padding(8.dp)) {
                            Surface(shape = RoundedCornerShape(topStart = 0.dp, topEnd = 12.dp, bottomEnd = 12.dp, bottomStart = 12.dp), color = MaterialTheme.colorScheme.surfaceVariant) {
                                Row(modifier = Modifier.padding(12.dp), horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                    repeat(3) { i ->
                                        Surface(shape = CircleShape, modifier = Modifier.size(8.dp), color = MaterialTheme.colorScheme.outline) {}
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Preset questions
            LazyRow(
                contentPadding = PaddingValues(horizontal = 16.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(presetQuestions) { q ->
                    SuggestionChip(onClick = { sendMessage(q) }, label = { Text(q, style = MaterialTheme.typography.labelSmall) })
                }
            }

            Spacer(Modifier.height(8.dp))

            // Input
            Row(
                modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),
                verticalAlignment = Alignment.Bottom,
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                OutlinedTextField(
                    value = input,
                    onValueChange = { input = it },
                    modifier = Modifier.weight(1f),
                    placeholder = { Text("Ask about savings, loans...") },
                    shape = RoundedCornerShape(24.dp),
                    maxLines = 3
                )
                FloatingActionButton(
                    onClick = { sendMessage(input) },
                    modifier = Modifier.size(52.dp),
                    containerColor = Primary,
                    contentColor = Color.White
                ) {
                    Icon(Icons.Default.Send, null)
                }
            }
        }
    }
}

@Composable
private fun ChatBubble(message: ChatMessage) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = if (message.isUser) Arrangement.End else Arrangement.Start
    ) {
        Surface(
            shape = RoundedCornerShape(
                topStart = if (message.isUser) 12.dp else 0.dp,
                topEnd = if (message.isUser) 0.dp else 12.dp,
                bottomEnd = 12.dp,
                bottomStart = 12.dp
            ),
            color = if (message.isUser) Primary else MaterialTheme.colorScheme.surfaceVariant,
            modifier = Modifier.widthIn(max = 300.dp)
        ) {
            Text(
                text = message.text,
                modifier = Modifier.padding(12.dp),
                style = MaterialTheme.typography.bodyMedium,
                color = if (message.isUser) Color.White else MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}
